In [ ]:
# 1. Create a numpy array with numpy.array module and with a data type integer and float
import numpy as np
array=np.array([1,2,3],dtype=int)
print(array)
print(type(array))
# float
float_array=np.array([1,2,4],dtype=float)
print(float_array)
print(type(array))

[1 2 3]
<class 'numpy.ndarray'>
[1. 2. 4.]
<class 'numpy.ndarray'>


In [ ]:
# 2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
# Also, print the shape and dimensions of the numpy arrays created above.
import numpy as np

# Zero-dimensional array
zero_dim = np.array(5)
print("Zero-dimensional array:")
print(zero_dim)
print("Shape:", zero_dim.shape)
print("Dimensions:", zero_dim.ndim)

# One-dimensional array
one_dim = np.array([1, 2, 3, 4, 5])
print("\nOne-dimensional array:")
print(one_dim)
print("Shape:", one_dim.shape)
print("Dimensions:", one_dim.ndim)

# Two-dimensional array
two_dim = np.array([[1, 2, 3], [4, 5, 6]])
print("\nTwo-dimensional array:")
print(two_dim)
print("Shape:", two_dim.shape)
print("Dimensions:", two_dim.ndim)

# Three-dimensional array
three_dim = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nThree-dimensional array:")
print(three_dim)
print("Shape:", three_dim.shape)
print("Dimensions:", three_dim.ndim)

# Four-dimensional array
four_dim = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("\nFour-dimensional array:")
print(four_dim)
print("Shape:", four_dim.shape)
print("Dimensions:", four_dim.ndim)



Zero-dimensional array:
5
Shape: ()
Dimensions: 0

One-dimensional array:
[1 2 3 4 5]
Shape: (5,)
Dimensions: 1

Two-dimensional array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2

Three-dimensional array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3

Four-dimensional array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Shape: (2, 2, 2, 2)
Dimensions: 4


In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
# 3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy.
print('2x2 matrix')
print(np.identity(2))
print('3x3 matrix')
print(np.identity(3))
print('4x4 matrix')
print(np.identity(4))

2x2 matrix
[[1. 0.]
 [0. 1.]]
3x3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4x4 matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 4. Create a numpy array with shape 2x5 that has all the elements as zero
np.zeros([2,5],dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Create a numpy array that has the shape 3x5 and all the elements are 5.
np.full([3,5],5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
# 6. Create a numpy array with random integers in the range 0-100, and the sample size should be 25.
np.arange(0,101,25)

array([  0,  25,  50,  75, 100])

In [ ]:
# 7. Create a numpy array with a shape 3x3 that has all elements as 1.
import numpy as np
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# 8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
#  Reshape the array in the shape 3x2 and print the updated shape of the resultant array.
np.random.randint(low=0, high = 100, size=(2,3))

array([[ 4, 83, 99],
       [20, 50, 50]])

In [ ]:
# 9. Create a random array, with the range 0-100, with a size 50. Perform the following operations on the same:
a=np.random.randint(0,100,50)
a

array([16,  4, 60, 73, 99, 74, 25, 76, 35,  8, 82, 47,  8,  8, 51, 52,  1,
       44, 27, 62, 68, 75, 72, 25, 47, 15,  3, 61, 81, 85, 33, 97, 17, 28,
       80, 28, 75, 24, 46, 53, 35, 99, 21, 56, 25, 61, 71, 53,  4, 73])

In [ ]:

# a. Print the first ten elements of the array
a[:10]

array([16,  4, 60, 73, 99, 74, 25, 76, 35,  8])

In [ ]:
# b. Print the last ten elements of the array print
a[40:]

array([35, 99, 21, 56, 25, 61, 71, 53,  4, 73])

In [ ]:
# c. Print the elements from the indexes 10-25
a[10:26]

array([82, 47,  8,  8, 51, 52,  1, 44, 27, 62, 68, 75, 72, 25, 47, 15])

In [ ]:

# d. Print the element at the index 22

a[22]

72

In [ ]:
#e. Print the array using negative indexing.
a[-15:-2]

array([28, 75, 24, 46, 53, 35, 99, 21, 56, 25, 61, 71, 53])

In [ ]:
# f. Print the last ten elements of the array, using negative indexing.
a[-10:]

array([35, 99, 21, 56, 25, 61, 71, 53,  4, 73])

In [ ]:
# 10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [ ]:
# Insert the element 6 at the end of the array.
b=np.insert(b,5,6)#np.insert(array,index,value)
b


array([1, 2, 3, 4, 5, 6])

In [ ]:
# b. Insert the element 10 at the beginning of the array.
b=np.insert(b,0,10)
b


array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
# c. Insert the element 30, before 4.
b=np.insert(b,4,30)
b


array([10,  1,  2,  3, 30,  4,  5,  6])

In [ ]:
# d. Update the element 5 as 50.
b[b==5]=50
b

array([10,  1,  2,  3, 30,  4, 50,  6])

In [ ]:

# e. Delete the element 50 in the updated array.

b=np.delete(b,6)
b

array([10,  1,  2,  3, 30,  4,  6])

In [ ]:
#f. Create a function to search for the element 30.
def fun(a):
  for i in range(0,len(b)):
    if b[i]==30:
      print(b[i],i)

In [ ]:
fun(a)

30 4


In [ ]:
#g. Sort the array in ascending order.
b.sort()
b

array([ 1,  2,  3,  4,  6, 10, 30])

**Numpy Operations**

This is the notes of Numpy Operations which helps to understand how to apply numpy to the data

In [2]:
import numpy as np

#1d array ---- it is a  vector
ary=np.array([1,2,3,4])
ary*2#it allows element wise operations

array([2, 4, 6, 8])

In [3]:
#2-Dimensional Array  ---- it is a metrix
#(rows,columns)
arr2d=np.array([[1,2,3],[4,5,6],[2,3,4]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

In [4]:
#Builtin functions
zero_matrix=np.zeros((3,4))
onedarray=np.zeros(5)
full=np.full((3,4),5)

In [5]:
a=np.arange(0,10,2) #step parameter
b=np.linspace(0,10,2)#how many values you want it will tell
c=np.random.random((2,3))
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
#Mathematical Functions
ary=np.array([1,2,3,4])
print(ary.sum())
print(np.sum(ary))
print(np.array([[10,20] ,[10,20]]))
print(np.sum([[10,20],[10,20]],axis = 0))  ## Column wise addition
print(np.sum([[10,20],[10,20]],axis = 1))  ## Row wise addition
print(np.add([10,20],[10,20]))#column wise addition
print(np.subtract([10,20],[10,20]))#column wise subtraction
print(np.diff([[10,20],[10,20]],axis = 0))  ## Column wise difference
print(np.diff([[10,20],[10,20]],axis = 1))  ## Row wise difference


10
10
[[10 20]
 [10 20]]
[20 40]
[30 30]
[20 40]
[0 0]
[[0 0]]
[[10]
 [10]]


In [11]:
a=np.arange(0,10,2)
b=np.arange(1,10,2)

print(np.multiply(a,b))#Multiplication
print(np.divide(a,b))#Division
print(np.exp(a))
print(np.sqrt(a))
np.sin(a)
np.cos(a)


[ 0  6 20 42 72]
[0.         0.66666667 0.8        0.85714286 0.88888889]
[1.00000000e+00 7.38905610e+00 5.45981500e+01 4.03428793e+02
 2.98095799e+03]
[0.         1.41421356 2.         2.44948974 2.82842712]


array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003])